version: "3.8"

services:
  ofelia:
    container_name: bom-bot-ofelia
    image: mcuadros/ofelia:latest
    depends_on:
      - bot
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  bot:
    build: .
    container_name: bom-bot-script
    command: ['tail', '-f', '/dev/null']
    volumes:
      - type: bind
        source: ./data
        target: /bom-bot/data
      - type: bind
        source: ./config
        target: /bom-bot/config
      - type: bind
        source: ./logs
        target: /bom-bot/logs
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "0 5 6 * * *"
      ofelia.job-exec.datecron.command: "/bin/sh /bom-bot/scripts/run.sh"
